version: '3.8'

services:
  ecblwebscraping:
    build:
      context: . # contexte de construction à la racine du projet
      dockerfile: etl/Dockerfile # chemin relatif vers le Dockerfile
    environment:
      - SERVICE_NAME=ecblwebscraping # variable d’environnement pour le service
    volumes:
      - ./logs:/app/logs # répertoire logs de l’hôte dans le conteneur
      - ./data:/app/data # répertoire data de l’hôte dans le conteneur
    networks:
      - ecblwebscraping_network # réseau dédié pour le service

networks:
  ecblwebscraping_network:

volumes:
  logs:
  data: