version: '3.8'

services:
  ecblwebscraping:
    build:
      context: . # contexte de construction à la racine du projet
      dockerfile: etl/Dockerfile.etl # chemin relatif vers le Dockerfile
    environment:
      - SERVICE_NAME=ecblwebscraping # variable d’environnement pour le service
    container_name: ecblwebscraping
    volumes:
      - ./logs:/app/logs # répertoire logs de l’hôte dans le conteneur
      - ./data:/app/data # répertoire data de l’hôte dans le conteneur
    networks:
      - my_ecobalyse_network # réseau dédié pour le service

  ecblredis:
    build:
      context: . # contexte de construction à la racine du projet
      dockerfile: redis/Dockerfile.redis # chemin relatif vers le Dockerfile pour Redis
    environment:
      - SERVICE_NAME=ecblredis # variable d’environnement pour le service
    container_name: ecblredis
    ports:
      - "6379:6379"
    volumes:
      - ./logs:/app/logs # répertoire logs de l’hôte dans le conteneur
      - ./data:/app/data # répertoire data de l’hôte dans le conteneur
    networks:
      - my_ecobalyse_network

  ecblmongodb:
    build:
      context: . # contexte de construction à la racine du projet
      dockerfile: mongo/Dockerfile.mongo # chemin relatif vers le Dockerfile pour MongoDB
    environment:
      - SERVICE_NAME=ecblmongodb # variable d’environnement pour le service
    container_name: ecblmongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db # répertoire data/mongo de l’hôte dans le conteneur
      - ./logs:/app/logs # répertoire logs de l’hôte dans le conteneur
      - ./data:/app/data # répertoire data de l’hôte dans le conteneur
    networks:
      - my_ecobalyse_network
  
  ecblflask:
    build:
      context: . # contexte de construction à la racine du projet
      dockerfile: flask/Dockerfile.flask # chemin relatif vers le Dockerfile pour Flask
    environment:
      - SERVICE_NAME=ecblflask # variable d’environnement pour le service
      - MONGO_URI=mongodb://ecblmongodb:27017
      - REDIS_URI=redis://ecblredis:6379
    container_name: ecblflask
    ports:
      - "5000:5000"
    depends_on:
      - ecblmongodb
      - ecblredis
    volumes:
      - ./logs:/app/logs # répertoire logs de l’hôte dans le conteneur
    networks:
      - my_ecobalyse_network

networks:
  my_ecobalyse_network:
    name: my_ecobalyse_network

volumes:
  logs:
  data: