# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /app

# copy the dependencies file to the working directory
COPY requirements.txt /app/requirements.txt

# install dependencies
RUN pip install --upgrade pip setuptools
RUN pip3 install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY . /app/

# create the logs directory
RUN mkdir -p /app/logs/etl

# make the file executable
RUN chmod +x start.sh

# exposing default port for streamlit
# EXPOSE 8501

# declare a volume
VOLUME /app/logs/etl

# command to run on container start : always active container
CMD ["bash", "-c", "./start.sh && tail -f /dev/null"]
