# Constantes Redis
ECOBALYSE_VER = "v2.4.0" # en date du 30/10/2024
REDIS_LOG_NAMEFILE = "docker_testredis"

PROG_FULL_MODE = True
JSON_BASIC_FILE = "PRJ-ECOBALYSE-TEXTILES_basic.json"
JSON_FULL_FILE = "PRJ-ECOBALYSE-TEXTILES_full.json"

PROG_ADM_RULE = True
PROG_NB_ITERATIONS = 5
